# Generated by Django 2.2.2 on 2019-06-20 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_movtorotativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movtorotativo',
            name='saida',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
